
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef WARNING_50X50_H
#define WARNING_50X50_H

#include "mxgui/image.h"

extern const mxgui::Image warning_50x50;

#endif //WARNING_50X50_H
